[package]
name = "logger"
version = "0.1.0"
edition = "2024"

[dependencies]
core = { path = "../core" }
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = [
    "rt-multi-thread",
    "macros",
    "net",
    "time",
    "signal"
] }
anyhow = "1"
bincode = "1.3.3"
