[package]
name = "master"
version = "0.1.0"
edition = "2024"

[dependencies]
core = { path = "../core" }
axum = "0.8.8"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dashmap = "6"